### ISSUE TITLE
Content improving

### ISSUE THREAD

**Issue by ArtemijRodionov** [fidals/fidals.com#6]
Хочу предложить правки по контенту. Изменения буду выделять жирным курсивом и они будут нести рекомендательный характер, если посчитаешь их несущественными, можешь не применять их. Так же буду оставлять замечания, которые можно будет обсудить.

### Главная страница:
>Команда Фидалс
Разрабатываем **_бэкэнд сервисы на аутсорсинге. Наш любимый язык - Python, с ним_** у нас больше всего опыта. **_Так же есть любимые инструменты/подходы_**: asyncio, postgres, docker, drone ci, github, kanban. Всегда можем выбрать **_другой язык или_** инструменты под проект, если это оправданно и всем выгодно.
Работаем по процессу pdd, принимаем оплату только за результат. 

изменил бы некоторые технологии в инструменты/подходы: asyncio на асинхронное программирование, drone ci на CI, добавил NoSQL и AMQP. Мне кажется это важно, т.к. прогеры, как котятки, играющие клубочками. Чем лучше клубочек, тем интереснее нам играть.

Возможно дополнил предложение про процесс pdd на PDD + [XDSD](http://www.xdsd.org/), т.к. pdd это только про декомпозицию задач и microtasking

### Страница "Разработчикам":
>Почему выбрали её:
>- Никаких джедайских знаний. Всё подуманное, сказанное и сделанное навсегда остаётся в гитхаб-репозитории проекта в **_виде комментариев_**.
>- Мгновенно и бескровно масштабирует **_скорость разработки проектов_**. Были бы ресурсы.
>- Позволяет исполнителям работать по 2-100ч в неделю без **_вреда?_** для процесса.
>- Оплата за результат.

Были бы ресурсы.

Не совсем понимаю, что имеется ввиду в этом предложении: "Позволяет исполнителям работать по 2-100ч в неделю без оверхеда для процесса.". 

>Как выглядит процесс
Реализацию любой задачи умещаем в определённое время. Обычно это один час. Если задача занимает больше одного часа, **_реализуем её часть и создаем подзадачи в комментариях к связанному коду специального todo формата_**.  При мерже в мастер-ветку гитхаб-**_бот_** создаст **_issues_**, **_из новых задач в комментариях слитого кода_**. **_Таким образом,_** рекурсивно **_делим_** задачи, пока они не станут размером в 1ч. **_~их уже просто реализовываем.~ Созданные_** задачи могут реализовывать разные исполнители. **_Задачи должны быть понятно описаны, чтобы с ними мог работать любой из разработчиков и находиться с релевантным кодом._**
~**_Любая задача имеет размер от 0.25пдд-ч до 2пдд-ч (пдд часы)_**~. Как только код задачи замержен в мастер, высылаем её исполнителю оплату за сделанный объём. Разработчик может отказаться от назначенной на него задачи в любой момент.
Делать задачу **_оцененную в 1 час можно 15 минут или 3 дня_** - это дело исполнителя, мы это никак не отслеживаем. Но после семи календарных дней после назначения можем снять задачу с исполнителя невзирая на её стадию.

Я бы сразу не снимал задачу с исполнителей после 7 дней. Было бы лучше уведомлять разработчика о том, что пары бы закрыть задачу, если он не отвечает или не успевает сделать это, в течении оговоренного времени, то снимаем с него задачу.

>Кому хорошо
Всем, и разработчикам тоже. Клиент выигрывает от этого подхода - он платит за гарантированно сделанную работу, а не за попытку её сделать. Этот выйгрыш мы частично закладываем в цену часа для исполнителя. Поэтому мы платим исполнителям выше рынка.
Мы **_используем PDD_** с Сентября 2017 года.

>Как начать с нами работать
Общаемся **_устно_** по связи. Это не техническое **_интервью, а_** просто знакомство. Вы сможете задать любые вопросы.
**_Вы_** выполняете пару простых **_оплачиваемых?_** задач, **_проходите код-ревью и сливаете код в мастер-ветку_**. У вас будет для этого до семи календарных дней.
Согласовываем договор, шлём текст с ним друг другу на email.
Начинаем работать **_по_** процессу.
За первые 20ч можем платить просто за потраченное время, а не **_по PDD_**. На ваш выбор.

**Comment by duker33** [comment]
@artemiy312 , некоторые замечания пофикшу, некоторые - нет. Обсуждать не будем, думаю у нас есть дела поважнее :)

**Comment by ArtemijRodionov** [comment]
Solved via #10
